import numpy as np

print("----------------------------------------------------------------")
A = np.array([1, 2, 3, 4])
print(A)
print(np.ndim(A))
print(A.shape)
print(A.shape[0])

print("----------------------------------------------------------------")
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)
print(np.ndim(B))
print(B.shape)

print("----------------------------------------------------------------")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))
print(np.dot(B, A))

print("----------------------------------------------------------------")
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
print(np.dot(A, B))
print(A.shape)
print(B.shape)
print(np.dot(A, B).shape)
print(np.dot(B, A))
print(np.dot(B, A).shape)

print("----------------------------------------------------------------")
X = np.array([1, 2])
print(X)
print(X.shape)
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)
print(W.shape)
Y = np.dot(X, W)
print(Y)
print(Y.shape)

print("----------------------------------------------------------------")
X = np.array([1, 2])
print(X)
print(X.shape)
W = np.array([[1], [2]])
print(W)
print(W.shape)
Y = np.dot(X, W)
print(Y)
print(Y.shape)
